import { VideoType, CommentType, UserProfileType } from './types';

// Mock videos for the feed
export const mockVideos: VideoType[] = [
  {
    id: 1,
    username: 'traveler',
    date: '2 days ago',
    caption: 'Exploring the beautiful beaches of Bali 🏝️ #travel #bali',
    audio: 'Original Sound - traveler',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://images.pexels.com/photos/3601421/pexels-photo-3601421.jpeg',
    likes: 2456,
    comments: 87,
    shares: 124,
  },
  {
    id: 2,
    username: 'foodie',
    date: '4 hours ago',
    caption: 'Making the perfect pasta from scratch 🍝 #cooking #homemade',
    audio: 'Cooking Sounds - foodie',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: 'https://images.pexels.com/photos/1527603/pexels-photo-1527603.jpeg',
    likes: 1872,
    comments: 142,
    shares: 56,
  },
  {
    id: 3,
    username: 'fitness_guru',
    date: '1 week ago',
    caption: '15-minute full body workout you can do at home 💪 #fitness #workout',
    audio: 'Workout Mix - DJ Fit',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnailUrl: 'https://images.pexels.com/photos/3757004/pexels-photo-3757004.jpeg',
    likes: 4281,
    comments: 235,
    shares: 312,
  },
  {
    id: 4,
    username: 'artist',
    date: '3 days ago',
    caption: 'Painting the sunset 🎨 #art #timelapse',
    audio: 'Chill Vibes - artist',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnailUrl: 'https://images.pexels.com/photos/6739710/pexels-photo-6739710.jpeg',
    likes: 3542,
    comments: 195,
    shares: 247,
  },
  {
    id: 5,
    username: 'pet_lover',
    date: '1 day ago',
    caption: 'My cat being adorable as usual 😻 #cats #pets',
    audio: 'Cute Sound - pet_lover',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    thumbnailUrl: 'https://images.pexels.com/photos/1643457/pexels-photo-1643457.jpeg',
    likes: 7832,
    comments: 421,
    shares: 652,
  },
];

// Mock comments for a reel
export const mockComments: CommentType[] = [
  {
    id: 1,
    username: 'user123',
    text: 'This is amazing! Love the editing 🔥',
    likes: 24,
    time: '2h ago',
    isAuthor: false,
  },
  {
    id: 2,
    username: 'traveler',
    text: 'Thank you all for the support! More content coming soon ❤️',
    likes: 56,
    time: '1h ago',
    isAuthor: true,
  },
  {
    id: 3,
    username: 'filmfan',
    text: 'What camera did you use for this?',
    likes: 3,
    time: '45m ago',
    isAuthor: false,
  },
  {
    id: 4,
    username: 'creative_mind',
    text: 'The colors in this video are perfect',
    likes: 12,
    time: '30m ago',
    isAuthor: false,
  },
  {
    id: 5,
    username: 'traveler',
    text: '@filmfan I used my iPhone 14 Pro',
    likes: 8,
    time: '20m ago',
    isAuthor: true,
  },
  {
    id: 6,
    username: 'photography_lover',
    text: 'I need to visit this place! Where exactly in Bali is this?',
    likes: 7,
    time: '15m ago',
    isAuthor: false,
  },
  {
    id: 7,
    username: 'nature_explorer',
    text: 'The soundtrack fits perfectly with this scenery 👌',
    likes: 9,
    time: '10m ago',
    isAuthor: false,
  },
  {
    id: 8,
    username: 'newuser',
    text: 'Just discovered your profile and I\'m already a fan!',
    likes: 2,
    time: '5m ago',
    isAuthor: false,
  },
];

// Mock user profile
export const mockUserProfile: UserProfileType = {
  username: 'creativecreator',
  name: 'Creative Creator',
  bio: 'Digital content creator | Travel enthusiast\nBringing stories to life through reels\n✨ New video every Wednesday',
  avatar: 'https://images.pexels.com/photos/1081685/pexels-photo-1081685.jpeg',
  website: 'https://www.creativecreator.com',
  reelsCount: 42,
  followers: 15200,
  following: 384,
  likes: 128900,
  reels: [
    {
      id: 101,
      thumbnailUrl: 'https://images.pexels.com/photos/2387873/pexels-photo-2387873.jpeg',
      likes: 2456,
      comments: 87,
    },
    {
      id: 102,
      thumbnailUrl: 'https://images.pexels.com/photos/3293148/pexels-photo-3293148.jpeg',
      likes: 1872,
      comments: 142,
    },
    {
      id: 103,
      thumbnailUrl: 'https://images.pexels.com/photos/4065183/pexels-photo-4065183.jpeg',
      likes: 4281,
      comments: 235,
    },
    {
      id: 104,
      thumbnailUrl: 'https://images.pexels.com/photos/3098970/pexels-photo-3098970.jpeg',
      likes: 3542,
      comments: 195,
    },
    {
      id: 105,
      thumbnailUrl: 'https://images.pexels.com/photos/3311574/pexels-photo-3311574.jpeg',
      likes: 7832,
      comments: 421,
      isPrivate: true,
    },
    {
      id: 106,
      thumbnailUrl: 'https://images.pexels.com/photos/5257534/pexels-photo-5257534.jpeg',
      likes: 1267,
      comments: 54,
    },
    {
      id: 107,
      thumbnailUrl: 'https://images.pexels.com/photos/3621344/pexels-photo-3621344.jpeg',
      likes: 2180,
      comments: 117,
    },
    {
      id: 108,
      thumbnailUrl: 'https://images.pexels.com/photos/3617457/pexels-photo-3617457.jpeg',
      likes: 5231,
      comments: 246,
    },
    {
      id: 109,
      thumbnailUrl: 'https://images.pexels.com/photos/4275885/pexels-photo-4275885.jpeg',
      likes: 3295,
      comments: 167,
      isPrivate: true,
    },
  ],
  savedReels: [
    {
      id: 201,
      thumbnailUrl: 'https://images.pexels.com/photos/1122868/pexels-photo-1122868.jpeg',
      likes: 4532,
      comments: 178,
    },
    {
      id: 202,
      thumbnailUrl: 'https://images.pexels.com/photos/1591373/pexels-photo-1591373.jpeg',
      likes: 2678,
      comments: 98,
    },
    {
      id: 203,
      thumbnailUrl: 'https://images.pexels.com/photos/3265460/pexels-photo-3265460.jpeg',
      likes: 3467,
      comments: 142,
    },
    {
      id: 204,
      thumbnailUrl: 'https://images.pexels.com/photos/3049121/pexels-photo-3049121.jpeg',
      likes: 1567,
      comments: 73,
    },
  ],
};